# Generated by Django 2.1.3 on 2018-11-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenShots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='img_api/static/')),
                ('created', models.DateTimeField()),
                ('coordinates', models.TextField(max_length=1024)),
            ],
        ),
    ]
