# Generated by Django 2.1.3 on 2018-11-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_api', '0002_auto_20181109_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshots',
            name='coordinates',
            field=models.TextField(default=None, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='created',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
