# Generated by Django 2.1.3 on 2018-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_api', '0004_auto_20181109_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshots',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_api/static/'),
        ),
    ]
