# Generated by Django 2.1.3 on 2018-11-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_api', '0005_auto_20181110_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshots',
            name='img',
            field=models.ImageField(blank=True, upload_to='img_api/static/screen_shots'),
        ),
    ]
