# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_api', '0012_auto_20181111_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshots',
            name='img',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
