# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-27 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_api', '0013_auto_20181120_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshots',
            name='img_name',
            field=models.TextField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='screenshots',
            name='img',
            field=models.ImageField(blank=True, upload_to='django_project/static'),
        ),
    ]
